service:
  name: aws-nodejs-typescript

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs6.10

functions:
  signup:
    handler: handler.signup
    events:
      - http:
          method: post
          path: signup

  bulkSignup:
    handler: handler.bulkSignup
    events:
      - http:
          method: get
          path: bulk_signup

  listUsers:
    handler: handler.listUsers
    events:
      - http:
          method: get
          path: list_users

